### ISSUE TITLE
MMD v3.0 Mod Vote: EverlastingAbilities

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#357]

**Comment by Aedda** [comment]
Abilities are far too easy to get even with a vanilla mob farm and have no upkeep costs and no limit to abilities owned/active. Diminishing saturation is a poor balance to power since bonemealer for instance can yield instant and unlimited crops from just 1 or 2 farmland, and the inclusion of an ability to counter hunger makes the mod just instantly cost free.

Some of the abilities are fine I feel but some completely negate other mechanics like Bonemealer making farming effortless for example.

**Comment by juryjr** [comment]
If this gets accepted can we disable bm absorption  and posible lower haste to 2  so it's not so op

**Comment by EPIICTHUNDERCAT** [comment]
UP UP vote UP
