### ISSUE TITLE
MMD v3.0 Mod Vote: EvilCraft

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#358]

**Comment by Aedda** [comment]
Voted up because this is a fun mod but the one bad really bad horrible horrible thing this mod does is create ghost mobs for every mob killed. This wrecks server performance for even small mob farms without the use of GemStone torches, which while cheap are still not free nor very known about. We need to maintain that any farm needs them, change the recipe, give them out as gifts, I dunno.
