### ISSUE TITLE
MMD v3.0 Mod Vote: WorldControl

### ISSUE THREAD

**Issue by Morpheus1101** [MinecraftModDevelopment/MMD-Dev-Server#404]

**Comment by Aedda** [comment]
This one may not get a completely fair vote but then again maybe that in itself is fair. Since this mod was specifically added to test features most testers would not see. Since there is no benefit to the server it is likely to be voted off.

I'm not sure MMD-dev is specifically the place for this sort of testing either.

I'll abstain just because I don't know where we should stand on hosting mods specifically for an author to test themselves.
